### ISSUE TITLE
link to slack not working

### ISSUE THREAD

**Issue by DerZyklop** [BeeToBeeOrg/docs#1]
is the channel 
#1_003_exchange_platform 
still existing?

**Comment by mskg** [comment]
It’s private send me your SlackID

Mit freundlichen Grüßen
Markus Kling

----

+49 (173) 6994372
markus.kling@gmail.com

Alt-Württemberg-Allee 57 | 71638 Ludwigsburg 

On 21. Mar 2020, at 16:57, DerZyklop <notifications@github.com> wrote:


is the channel
#1_003_exchange_platform
still existing?

**Comment by DerZyklop** [comment]
#README.md:16[README.md:16](url)
